### PR TITLE
Use enum for view type

### PR DESCRIPTION
**Pull request by bryant1410**

### CODE REVIEW

**Comment by kanytu** [comment]
Rejected:
Look at
http://developer.android.com/training/articles/perf-tips.html#avoid_enums

**Comment by bryant1410** [comment]
:open_mouth:

**Comment by bryant1410** [comment]
where is the avoid enums part?

**Comment by bryant1410** [comment]
http://stackoverflow.com/questions/5143256/why-was-avoid-enums-where-you-only-need-ints-removed-from-androids-performanc

**Comment by kanytu** [comment]
The question is why changing it for enums?

**Comment by bryant1410** [comment]
I think they are made for this type of things

**Comment by kanytu** [comment]
http://developer.android.com/training/articles/memory.html#Overhead

Enums often require more than twice as much memory as static constants. You should strictly avoid using enums on Android.

**Comment by bryant1410** [comment]
I think this is splitting hairs. Anyway, I think it's ok to keep it without enums

**Pull request closed without merging**
